server:
  port: 8888

spring:
    application:
        name: config-server
    cloud:
      config:
        server:
          git:
            default-label: master
            uri: https://github.com/LEEHYUNDONG/cloud-config-demo
            search-paths: cloud-config-file/**
            basedir: ./repo

