server:
  port: 8888

spring:
    application:
        name: config
    cloud:
        config:
          server:
            git: https://github:com/LEEHYUNDONG/msa-cloud-config
            default: main
